import { randomUUID } from 'node:crypto';
import pg from 'pg';
import { inject } from 'vitest';
import { createPool, withTenant } from '../../packages/db/src/client.js';
import { DerivedTenantKeyProvider } from '../../packages/core/src/crypto/tenant-keys.js';
import { StaticMasterKeySource } from '../../packages/core/src/crypto/master-key.js';
import type { TenantKeyProvider } from '../../packages/core/src/crypto/tenant-keys.js';
import { quoteIdentifier } from '../../packages/db/src/sql-identifier.js';
import { TEST_ROLE_PASSWORDS } from './constants.js';

/**
 * Each test file gets its own database cloned from the migrated template, so suites can
 * never observe each other's rows and a failure is always reproducible on its own.
 *
 * Rule 12 in practice: the guards connect through `appPool` and `retentionPool`, never as
 * the owner. A guard that connects as the owner bypasses every policy and turns green
 * while proving nothing.
 */

export interface TestDatabase {
  /** Application role. Owns nothing, never bypasses row level security. */
  appPool: pg.Pool;
  /** Retention role. The only role holding DELETE on attestations. */
  retentionPool: pg.Pool;
  /** Owner role. Migrations and inspection only, never used to prove isolation. */
  migratorPool: pg.Pool;
  /** Connection string for the application role, for code that builds its own pool. */
  appConnectionString: string;
  databaseName: string;
  close: () => Promise<void>;
}

function urlFor(base: string, database: string, user: string, password: string): string {
  const url = new URL(base);
  url.pathname = `/${database}`;
  url.username = user;
  url.password = password;
  return url.toString();
}

export async function createTestDatabase(): Promise<TestDatabase> {
  const baseUrl = inject('pgBaseUrl');
  const template = inject('templateDatabase');
  const databaseName = `nx_test_${randomUUID().replaceAll('-', '')}`;

  const admin = new pg.Client({ connectionString: baseUrl });
  await admin.connect();
  await admin.query(
    `CREATE DATABASE ${quoteIdentifier(databaseName)} TEMPLATE ${quoteIdentifier(template)}`,
  );
  await admin.end();

  const appPool = createPool(urlFor(baseUrl, databaseName, 'nx_app', TEST_ROLE_PASSWORDS.nx_app));
  const retentionPool = createPool(
    urlFor(baseUrl, databaseName, 'nx_retention', TEST_ROLE_PASSWORDS.nx_retention),
  );
  const migratorPool = createPool(
    urlFor(baseUrl, databaseName, 'nx_migrator', TEST_ROLE_PASSWORDS.nx_migrator),
  );

  return {
    appPool,
    retentionPool,
    migratorPool,
    appConnectionString: urlFor(baseUrl, databaseName, 'nx_app', TEST_ROLE_PASSWORDS.nx_app),
    databaseName,
    close: async () => {
      await Promise.all([appPool.end(), retentionPool.end(), migratorPool.end()]);
      const cleanup = new pg.Client({ connectionString: baseUrl });
      await cleanup.connect();
      await cleanup.query(`DROP DATABASE IF EXISTS ${quoteIdentifier(databaseName)} WITH (FORCE)`);
      await cleanup.end();
    },
  };
}

export interface SeededTenant {
  tenantId: string;
  entityId: string;
}

/**
 * ADR-011: no role in this system holds BYPASSRLS, so creating a tenant cannot take a
 * shortcut around the policy. The tenant id is generated by the caller, put into scope,
 * and then the row is inserted, which satisfies the policy's WITH CHECK on its own row.
 * Tenant creation walks the same path as everything else.
 */
export async function seedTenant(pool: pg.Pool, legalName: string): Promise<SeededTenant> {
  const tenantId = randomUUID();
  const entityId = randomUUID();

  await withTenant(pool, tenantId, async (tx) => {
    await tx.query('INSERT INTO tenants (id, legal_name) VALUES ($1, $2)', [tenantId, legalName]);
    await tx.query(
      'INSERT INTO entities (id, tenant_id, entity_type, display_name) VALUES ($1, $2, $3, $4)',
      [entityId, tenantId, 'BUSINESS', legalName],
    );
  });

  return { tenantId, entityId };
}

export interface InsertAttestationOptions {
  fieldPath?: string;
  value?: unknown;
  observedAt?: Date;
  validUntil?: Date | null;
}

export async function insertAttestation(
  pool: pg.Pool,
  tenant: SeededTenant,
  options: InsertAttestationOptions = {},
): Promise<string> {
  const fieldPath = options.fieldPath ?? 'cr.status';
  const value = options.value ?? { status: 'active' };
  const observedAt = options.observedAt ?? new Date();

  return withTenant(pool, tenant.tenantId, async (tx) => {
    const { rows } = await tx.query<{ id: string }>(
      `INSERT INTO attestations
         (tenant_id, entity_id, field_path, value, value_hash, source, authority,
          run_id, observed_at, valid_from, valid_until)
       VALUES ($1, $2, $3, $4::jsonb, sha256($4::text::bytea), $5, $6, $7, $8, $8, $9)
       RETURNING id`,
      [
        tenant.tenantId,
        tenant.entityId,
        fieldPath,
        JSON.stringify(value),
        'provider.stub',
        'MC',
        randomUUID(),
        observedAt,
        options.validUntil ?? null,
      ],
    );
    const id = rows[0]?.id;
    if (!id) {
      throw new Error('attestation insert returned no id');
    }
    return id;
  });
}

/**
 * A deterministic master key for tests. Real environments read it from a KMS through
 * MasterKeySource, and it never reaches the database in either case (rule 10).
 */
export function testKeys(): TenantKeyProvider {
  return new DerivedTenantKeyProvider(new StaticMasterKeySource(Buffer.alloc(32, 7)));
}

/** Creates an additional entity inside an existing tenant. */
export async function seedEntity(
  pool: pg.Pool,
  tenantId: string,
  entityType = 'PERSON',
  displayName = 'Seeded Entity',
): Promise<string> {
  return withTenant(pool, tenantId, async (tx) => {
    const { rows } = await tx.query<{ id: string }>(
      'INSERT INTO entities (tenant_id, entity_type, display_name) VALUES ($1, $2, $3) RETURNING id',
      [tenantId, entityType, displayName],
    );
    const id = rows[0]?.id;
    if (!id) {
      throw new Error('entity insert returned no id');
    }
    return id;
  });
}
